name: eua_ui
description: "Simple email user agent implemented in Flutter & Rust."

publish_to: "none"

version: 0.5.9

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  another_flutter_splash_screen: ^1.2.0
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.3
  flex_color_picker: ^3.5.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  protobuf: ^3.1.0
  provider: ^6.0.5
  rinf: ^6.10.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.7
  pedantic_mono: any

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "lib/images/e-mail.png"
    icon_size: 48

flutter:
  fonts:
    - family: DingTalk
      fonts:
        - asset: packages/eua_ui/fonts/DingTalkJinBuTi.ttf
    - family: JetbrainsMONO
      fonts:
        - asset: packages/eua_ui/fonts/JetBrainsMono-SemiBold.ttf
    - family: Inter
      fonts:
        - asset: packages/eua_ui/fonts/InterDisplay-Regular.ttf
  assets:
    - packages/eua_ui/images/github-mark.png
    - packages/eua_ui/images/github-mark-white.png
    - packages/eua_ui/images/splash.png
  uses-material-design: true

msix_config:
  display_name: eua_ui
  publisher_display_name: Somnia1337
  identity_name: somnia1337.eua-ui
  msix_version: 0.5.9.0
  logo_path: D:\Image\Logo\Icon\EUA.ico
  capabilities: internetClient
  certificate_path: D:\Apps\Somnia1337Certificate.pfx
  certificate_password: SomCERTIFICATE1337
