[package]
# Do not change the name of this crate.
name = "hub"
version = "0.4.0"
edition = "2021"

[lib]
# `lib` is required for non-library targets,
# such as tests and benchmarks.
# `cdylib` is for Linux, Android, Windows, and web.
# `staticlib` is for iOS and macOS.
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
rinf = "6.8.0"
prost = "0.12.3"
wasm-bindgen = "0.2.91"
tokio_with_wasm = "0.4.3"
sample_crate = { path = "../sample_crate" }
imap = "3.0.0-alpha.14"
lettre = "0.11.7"
native-tls = "0.2.11"
